<div class="splitToolbarButton">
    <button class="toolbarButton pageUp" title="Previous Page" id="previous" tabindex="7" data-l10n-id="previous" data-target="<?php echo $this->previous; ?>"  >
        <span data-l10n-id="previous_label">Previous</span>
    </button>
    <div class="splitToolbarButtonSeparator"></div>
    <button class="toolbarButton pageDown" title="Next Page" id="next" tabindex="8" data-l10n-id="next" data-target="<?php echo $this->next; ?>" >
        <span data-l10n-id="next_label">Next</span>
    </button>
</div>
<label id="pageNumberDDSLabel" class="toolbarLabel" for="pageNumber" data-l10n-id="page_label" >Scan: </label>
<input type="number" id="pageDDSNumber"  name="scan-number" class="toolbarField pageNumber" value="<?php echo $this->firstItemNumber; ?>" size="4" min="1" tabindex="9">



<input type="number" id="totalPages" value="<?php echo $this->totalItemCount; ?>" style="display:none;" >
<span id="numDDSPages" class="toolbarLabel" > of <?php echo $this->totalItemCount; ?></span>


