<div class="page-header">
    <h3>CRL Shibboleth</h3>
</div>
<div class="col-md-12">

    <div class="panel panel-default">

        <div class="panel-body">
            <?php
            if ($this->logged) {
                ?>  
                <div class="alert alert-success" role="alert">
                    You are authorized to access the resources in this site. You do not need to authenticate again. 
                </div>
                <?php
            }
            ?>
            <div id="idpSelect"></div>
            <script src="ds/idpselect_config.js" type="text/javascript" language="javascript"></script>

            <script src="ds/idpselect.js" type="text/javascript" language="javascript"></script>
<?php
echo $this->headLink()->appendStylesheet($this->basePath() . 'ds/idpselect.css');
?>
            <noscript>
            <!-- If you need to care about non javascript browsers you will need to 
                 generate a hyperlink to a non-js DS.
        
                 To build you will need:
                     - URL:  The base URL of the DS you use
                     - EI: Your entityId, URLencoded.  You can get this from the line that 
                       this page is called with.
                     - RET: Your return address dlib-adidp.ucs.ed.ac.uk. Again you can get
                       this from the page this is called with, but beware of the 
                       target%3Dcookie%253A5269905f bit..
        
                < href=${URL}?entityID=${EI}&return=${RET}
            -->

            Your Browser does not support javascript. Please use 
            <a href="http://federation.org/DS/DS?entityID=https%3A%2F%2FyourentityId.edu.edu%2Fshibboleth&return=https%3A%2F%2Fyourreturn.edu%2FShibboleth.sso%2FDS%3FSAMLDS%3D1%26target%3Dhttps%3A%2F%2Fyourreturn.edu%2F">this link</a>.

            </noscript>

            <small> Only CRL member institutions which belong to the <a href="http://www.incommon.org/participants/">InCommon federation</a> are included. Visit <a href="http://www.crl.edu/shibboleth">CRL Shibboleth</a> information page for more details.</small>
<?php // } ?>
        </div>
    </div>
</div>
<div style="clear:both;"></div>
