<!-- Le styles -->
<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/viewer.css')
;

echo $this->headScript()
        ->prependFile($this->basePath() . '/js/viewer.js')
        ->prependFile($this->basePath() . '/js/l10n.js')
        ->prependFile($this->basePath() . '/js/compatibility.js')
        ->prependFile($this->basePath() . '/js/pdf.js')
        ->prependFile($this->basePath() . '/js/debugger.js')

;
$this->headTitle($item->title->title);
?>
<div class="page-header">
    <h3>
        <?php echo $item->title->title; ?>  

         <a class="btn btn-default btn-xs pull-right" data-toggle="modal" data-target=".bs-help-modal-lg" ><span class="glyphicon glyphicon-share-alt"></span> Viewer Information </a>
        <a style="margin-right: 5px;"href="<?php echo $this->url('dds-title', array('action' => 'index', 'id' => $item->title->tid)) ?>" class="btn btn-default btn-xs pull-right"  role="button"><span class="glyphicon glyphicon-share-alt"></span>&nbsp;&nbsp;Back to Title </a>
    </h3> 
    <div class="modal fade bs-help-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">PDF Viewer Information</h4>
                </div>
                <div class="modal-body">
                    <p>The PDF viewer deployed on this site works the best with browsers supporting HTML 5. Using an older Web browser on your computer could cause difficulties in viewing the page images. In that case, please upgrade your browser or try to open the page from a different browser. Or, you may download the PDF files first, and then open it with your Acrobat Reader.  </p>
                    <p>If the issue persists, please contact <a href="mailto:ashrestha@crl.edu">CRL Systems</a> for additional instructions. Thank you for your patience. 
                    </p>
                </div>


            </div>
        </div>
    </div>
</div>



<div class="col-md-12" id="ddsViewer"> 
    <h4> <?php echo $item->item_text; ?> </h4>
    <div class="panel panel-default" id="ddsViewerPanel">

        <div class="panel-heading" id="ddsViewerHead">


            <div id="outerContainer" class="loadingInProgress" >

                <div id="sidebarContainer">

                    <div id="sidebarContent">
                        <div id="thumbnailView">
                        </div>

                    </div>
                </div>  <!-- sidebarContainer -->

                <div id="mainContainer">
                    <div class="findbar hidden doorHanger hiddenSmallView" id="findbar">
                        <label for="findInput" class="toolbarLabel" data-l10n-id="find_label">Find:</label>
                        <input id="findInput" class="toolbarField" tabindex="41">
                        <div class="splitToolbarButton">
                            <button class="toolbarButton findPrevious" title="" id="findPrevious" tabindex="42" data-l10n-id="find_previous">
                                <span data-l10n-id="find_previous_label">Previous</span>
                            </button>
                            <div class="splitToolbarButtonSeparator"></div>
                            <button class="toolbarButton findNext" title="" id="findNext" tabindex="43" data-l10n-id="find_next">
                                <span data-l10n-id="find_next_label">Next</span>
                            </button>
                        </div>
                        <input type="checkbox" id="findHighlightAll" class="toolbarField">
                        <label for="findHighlightAll" class="toolbarLabel" tabindex="44" data-l10n-id="find_highlight">Highlight all</label>
                        <input type="checkbox" id="findMatchCase" class="toolbarField">
                        <label for="findMatchCase" class="toolbarLabel" tabindex="45" data-l10n-id="find_match_case_label">Match case</label>
                        <span id="findMsg" class="toolbarLabel"></span>
                    </div>  <!-- findbar -->

                    <div id="secondaryToolbar" class="secondaryToolbar hidden doorHangerRight">
                        <div id="secondaryToolbarButtonContainer">

                            <button id="secondaryPresentationMode" class="secondaryToolbarButton presentationMode visibleLargeView" title="Switch to Presentation Mode" tabindex="19" data-l10n-id="presentation_mode">
                                <span data-l10n-id="presentation_mode_label">Presentation Mode</span>
                            </button>



                            <button id="secondaryDownload" class="secondaryToolbarButton download visibleMediumView" title="Download" tabindex="22" data-l10n-id="download" >
                                <span data-l10n-id="download_label">Download</span>
                            </button>




                            <button id="previousIssue" class="secondaryToolbarButton firstPage" title="Go to Previous Issue" tabindex="24" data-l10n-id="previous_issue" onclick="window.location.href = '<?php echo ($this->item_previous) ? $this->url('dds-item', array('action' => 'index', 'id' => $this->item_previous->iid)) : "#"; ?>';" <?php echo ($this->item_previous) ? '' : 'disabled'; ?>>
                                <span data-l10n-id="previous_issue_label">Go to Previous Issue</span>
                            </button>
                            <button id="nextIssue" class="secondaryToolbarButton lastPage" title="Go to Next Issue" tabindex="25" data-l10n-id="next_issue" onclick="window.location.href = '<?php echo ($this->item_next) ? $this->url('dds-item', array('action' => 'index', 'id' => $this->item_next->iid)) : "#" ?>';" <?php echo ($this->item_next) ? '' : 'disabled'; ?>>
                                <span data-l10n-id="next_issue_label">Go to Next Issue</span>
                            </button>

                            <div class="horizontalToolbarSeparator"></div>

                            <button id="pageRotateCw" class="secondaryToolbarButton rotateCw" title="Rotate Clockwise" tabindex="26" data-l10n-id="page_rotate_cw">
                                <span data-l10n-id="page_rotate_cw_label">Rotate Clockwise</span>
                            </button>
                            <button id="pageRotateCcw" class="secondaryToolbarButton rotateCcw" title="Rotate Counterclockwise" tabindex="27" data-l10n-id="page_rotate_ccw">
                                <span data-l10n-id="page_rotate_ccw_label">Rotate Counterclockwise</span>
                            </button>

                            <div class="horizontalToolbarSeparator"></div>

                            <button id="toggleHandTool" class="secondaryToolbarButton handTool" title="Enable hand tool" tabindex="28" data-l10n-id="hand_tool_enable">
                                <span data-l10n-id="hand_tool_enable_label">Enable hand tool</span>
                            </button>

                            <div class="horizontalToolbarSeparator"></div>

                            <button id="documentProperties" class="secondaryToolbarButton documentProperties" title="Document Properties…" tabindex="29" data-l10n-id="document_properties">
                                <span data-l10n-id="document_properties_label">Document Properties</span>
                            </button>
                        </div>
                    </div>  <!-- secondaryToolbar -->

                    <div class="toolbar">
                        <div id="toolbarContainer">
                            <div id="toolbarViewer">
                                <div id="toolbarViewerLeft">

                                    <button id="viewFind" class="toolbarButton group hiddenSmallView" title="Find in Document" tabindex="6" data-l10n-id="findbar">
                                        <span data-l10n-id="findbar_label">Find</span>
                                    </button>
                                    <!-- Pagination Start -->
                                    <p></p>
                                    <?php
                                    echo $this->paginationControl(
                                            // the paginator object
                                            $paginator,
                                            // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                                            'sliding',
                                            // the partial to use to render the control
                                            array('partial/paginator_viewer', 'Dds'),
                                            // the route to link to when a user clicks a control link
                                            array(
                                        'route' => 'dds-scan',
                                        'id' => $item->iid,
                                        'item_previous' => $item_previous,
                                        'item_next' => $item_next,
                                            )
                                    );
                                    ?>
                                    <!-- Pagination End -->

                                </div>
                                <div id="toolbarViewerRight">
                                    <button id="presentationMode" class="toolbarButton presentationMode hiddenLargeView"  title="Switch to Presentation Mode" tabindex="13" data-l10n-id="presentation_mode">
                                        <span data-l10n-id="presentation_mode_label">Presentation Mode</span>
                                    </button>
                                    <button id="download" class="toolbarButton download hiddenMediumView" title="Download" tabindex="16" data-l10n-id="download" onclick="window.location.href = '<?php echo $this->url('dds-scan', array('action' => 'download', 'id' => $item->iid, 'f' => $params->fromRoute('f'))); ?>';" >
                                        <span data-l10n-id="download_label">Download</span>
                                    </button>
                                    <button id="secondaryToolbarToggle" class="toolbarButton" title="Tools" tabindex="18" data-l10n-id="tools" >
                                        <span data-l10n-id="tools_label">Tools</span>
                                    </button> 
                                </div>
                                <div class="outerCenter">
                                    <div class="innerCenter" id="toolbarViewerMiddle">
                                        <div class="splitToolbarButton">
                                            <button id="zoomOut" class="toolbarButton zoomOut" title="Zoom Out" tabindex="10" data-l10n-id="zoom_out">
                                                <span data-l10n-id="zoom_out_label">Zoom Out</span>
                                            </button>
                                            <div class="splitToolbarButtonSeparator"></div>
                                            <button id="zoomIn" class="toolbarButton zoomIn" title="Zoom In" tabindex="11" data-l10n-id="zoom_in">
                                                <span data-l10n-id="zoom_in_label">Zoom In</span>
                                            </button>
                                        </div>
                                        <span id="scaleSelectContainer" class="dropdownToolbarButton">
                                            <select id="scaleSelect" title="Zoom" tabindex="12" data-l10n-id="zoom">
                                                <option id="pageAutoOption" title="" value="auto" selected="selected" data-l10n-id="page_scale_auto">Automatic Zoom</option>
                                                <option id="pageActualOption" title="" value="page-actual" data-l10n-id="page_scale_actual">Actual Size</option>
                                                <option id="pageFitOption" title="" value="page-fit" data-l10n-id="page_scale_fit">Fit Page</option>
                                                <option id="pageWidthOption" title="" value="page-width" data-l10n-id="page_scale_width">Full Width</option>
                                                <option id="customScaleOption" title="" value="custom"></option>
                                                <option title="" value="0.5">50%</option>
                                                <option title="" value="0.75">75%</option>
                                                <option title="" value="1">100%</option>
                                                <option title="" value="1.25">125%</option>
                                                <option title="" value="1.5">150%</option>
                                                <option title="" value="2">200%</option>
                                            </select>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div id="loadingBar">
                                <div class="progress">
                                    <div class="glimmer">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <menu type="context" id="viewerContextMenu">
                        <menuitem id="contextFirstPage" label="Previous Issue"
                                  data-l10n-id="previous_issue"></menuitem>
                        <menuitem id="contextLastPage" label="Next Issue"
                                  data-l10n-id="next_issue"></menuitem>
                        <menuitem id="contextPageRotateCw" label="Rotate Clockwise"
                                  data-l10n-id="page_rotate_cw"></menuitem>
                        <menuitem id="contextPageRotateCcw" label="Rotate Counter-Clockwise"
                                  data-l10n-id="page_rotate_ccw"></menuitem>
                    </menu>



                    <div id="errorWrapper" hidden='true'>
                        <div id="errorMessageLeft">
                            <span id="errorMessage"></span>
                            <button id="errorShowMore" data-l10n-id="error_more_info">
                                More Information
                            </button>
                            <button id="errorShowLess" data-l10n-id="error_less_info" hidden='true'>
                                Less Information
                            </button>
                        </div>
                        <div id="errorMessageRight">
                            <button id="errorClose" data-l10n-id="error_close">
                                Close
                            </button>
                        </div>
                        <div class="clearBoth"></div>
                        <textarea id="errorMoreInfo" hidden='true' readonly="readonly"></textarea>
                    </div>
                </div> <!-- mainContainer -->

                <div id="overlayContainer" class="hidden">

                    <div id="documentPropertiesContainer" class="hidden">
                        <div class="doorHanger">
                            <div class="row">
                                <span data-l10n-id="document_properties_file_name">File name:</span> <p id="fileNameField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_file_size">File size:</span> <p id="fileSizeField">-</p>
                            </div>
                            <div class="separator"></div>
                            <div class="row">
                                <span data-l10n-id="document_properties_title">Title:</span> <p id="titleField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_author">Author:</span> <p id="authorField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_subject">Subject:</span> <p id="subjectField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_keywords">Keywords:</span> <p id="keywordsField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_creation_date">Creation Date:</span> <p id="creationDateField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_modification_date">Modification Date:</span> <p id="modificationDateField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_creator">Creator:</span> <p id="creatorField">-</p>
                            </div>
                            <div class="separator"></div>
                            <div class="row">
                                <span data-l10n-id="document_properties_producer">PDF Producer:</span> <p id="producerField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_version">PDF Version:</span> <p id="versionField">-</p>
                            </div>
                            <div class="row">
                                <span data-l10n-id="document_properties_page_count">Page Count:</span> <p id="pageCountField">-</p>
                            </div>
                            <div class="buttonRow">
                                <button id="documentPropertiesClose" class="overlayButton"><span data-l10n-id="document_properties_close">Close</span></button>
                            </div>
                        </div>
                    </div>
                </div>  <!-- overlayContainer -->

            </div> <!-- outerContainer -->
        </div>

        <div class="panel-body" id="ddsViewerBody"> 


            <div id="viewerContainer" tabindex="0">
                <div id="viewer"></div>
            </div>
            <div id="printContainer"></div>
            <div id="mozPrintCallback-shim" hidden>
                <style scoped>
                    #mozPrintCallback-shim {
                        position: fixed;
                        top: 0;
                        left: 0;
                        height: 100%;
                        width: 100%;
                        z-index: 9999999;

                        display: block;
                        text-align: center;
                        background-color: rgba(0, 0, 0, 0.5);
                    }
                    #mozPrintCallback-shim[hidden] {
                        display: none;
                    }
                    @media print {
                        #mozPrintCallback-shim {
                            display: none;
                        }
                    }

                    #mozPrintCallback-shim .mozPrintCallback-dialog-box {
                        display: inline-block;
                        margin: -50px auto 0;
                        position: relative;
                        top: 45%;
                        left: 0;
                        min-width: 220px;
                        max-width: 400px;

                        padding: 9px;

                        border: 1px solid hsla(0, 0%, 0%, .5);
                        border-radius: 2px;
                        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);

                        background-color: #474747;

                        color: hsl(0, 0%, 85%);
                        font-size: 16px;
                        line-height: 20px;
                    }
                    #mozPrintCallback-shim .progress-row {
                        clear: both;
                        padding: 1em 0;
                    }
                    #mozPrintCallback-shim progress {
                        width: 100%;
                    }
                    #mozPrintCallback-shim .relative-progress {
                        clear: both;
                        float: right;
                    }
                    #mozPrintCallback-shim .progress-actions {
                        clear: both;
                    }
                    //This for the canvas scroll
                    .canvasWrapper{
                        top:10px;
                        left:10px;
                        width: 318px; /* adjusted hard-coded scrollbar width; you should set this with js */
                        height: 300px;
                        border: 2px solid black;
                        margin:30px 0 2;
                        overflow-y: scroll; /* scrolling vertical only */
                        overflow-x: hidden; /* hiding horizontal scrollbar */
                    }
                </style>
                <div class="mozPrintCallback-dialog-box">
                    <!-- TODO: Localise the following strings -->
                    Preparing document for printing...
                    <div class="progress-row">
                        <progress value="0" max="100"></progress>
                        <span class="relative-progress">0%</span>
                    </div>
                    <div class="progress-actions">
                        <input type="button" value="Cancel" class="mozPrintCallback-cancel">
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<div style="clear:both;"></div>
