<!-- Le styles -->
<?php
$this->headTitle($item->title->title);
?>
<div class="page-header">
    <h3>
        <?php echo $item->title->title; ?>  

         <a class="btn btn-default btn-xs pull-right" data-toggle="modal" data-target=".bs-help-modal-lg" ><span class="glyphicon glyphicon-share-alt"></span> Viewer Information </a>
        <a style="margin-right: 5px;"href="<?php echo $this->url('dds-title', array('action' => 'index', 'id' => $item->title->tid)) ?>" class="btn btn-default btn-xs pull-right"  role="button"><span class="glyphicon glyphicon-share-alt"></span>&nbsp;&nbsp;Back to Title </a>
    </h3> 
    <div class="modal fade bs-help-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">PDF Viewer Information</h4>
                </div>
                <div class="modal-body">
                    <p>The PDF viewer deployed on this site works the best with browsers supporting HTML 5. Using an older Web browser on your computer could cause difficulties in viewing the page images. 
                        In that case, please upgrade your browser or try to open the page from a different browser. 
                        You may also switch to the <a href="<?php echo $this->url('dds-item', array('action' => 'index', 'id' => $this->item->iid)).'?viewer=iframe'; ?>">browser based viewer</a> or, you may download the PDF files first, and then open it with your Acrobat Reader.  </p>
                    <p>If the issue persists, please contact <a href="mailto:ashrestha@crl.edu">CRL Systems</a> for additional instructions. Thank you for your patience. 
                    </p>
                </div>


            </div>
        </div>
    </div>
</div>
<div class="col-md-12" id="ddsViewer"> 
    <h4> <?php echo $item->item_text; ?> </h4>

<?php echo $viewer;?>
</div>