<div class="page-header">
    <h3>Rights statement</h3>
</div>

<div class="col-md-12" id="accordion">

    <div class="panel panel-default">

        <div class="panel-body">
           PLACEHOLDER TEXT
           
           Materials digitized by the Center for Research Libraries are intended for the personal educational and research use of students, scholars, and other researchers of the CRL member community. Copyrighted images and texts are not to be reproduced, displayed, distributed, broadcast, or downloaded for other purposes without the expressed, written permission of the copyright owner.
        </div>

    </div>
    